source/config/routes.rb
MyFitness::Application.routes.draw do
  #resources :participant_profiles

  #resources :fitness_goals

  #resources :participants

  resources :participants do
    resources :fitness_goals
    resources :participant_profiles

    collection do
      get 'welcome' #welcome page
      post 'find' #find a participant by email
      get 'list' #list all participants registered in the system
    end

  end
  
  root :to => 'participants#welcome'

end

source/app/models/participant_profile.rb
class ParticipantProfile < ActiveRecord::Base
  belongs_to :participant
end

source/app/controllers/participant_profiles_controller.rb
class ParticipantProfilesController < ApplicationController
  include Databasedotcom::Rails::Controller
  #http_basic_authenticate_with :name => "ray", :password => "xxx", :except => :index

  before_filter :init

  def init
    dbdc_client.materialize('Participant__c')
    dbdc_client.materialize('ParticipantProfile__c')
    dbdc_client.materialize('Fitness_Goal__c')

    @dbdc_client = dbdc_client
  end
  
  # GET /participant_profiles
  # GET /participant_profiles.json
  def index
    @participant = Participant__c.find(request[:participant_id])
    @participant_profiles = ParticipantProfile__c.query("Participant__r.Id=" + "'#{request[:participant_id]}'")
    #render :text => 'result is here.'

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @participant_profiles }
    end

  end

  # GET /participant_profiles/1
  # GET /participant_profiles/1.json
  def show
    @participant = Participant__c.find(request[:participant_id])
    @participant_profile = ParticipantProfile__c.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @participant_profile }
    end
  end

  # GET /participant_profiles/new
  # GET /participant_profiles/new.json
  def new
    @participant = Participant__c.find(request[:participant_id])
    @participant_profile = ParticipantProfile__c.new
    @operation = 'create'

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @participant_profile }
    end
  end

  # GET /participant_profiles/1/edit
  def edit
    @participant = Participant__c.find(request[:participant_id])
    @participant_profile = ParticipantProfile__c.find(params[:id])
    @operation = 'update'
  end

  # POST /participant_profiles
  # POST /participant_profiles.json
  def create
    @participant = Participant__c.find(request[:participant_id])
    params[:participant_profile__c]['Participant__c'] = @participant['Id']
    participant_profile = ParticipantProfile__c.coerce_params(params[:participant_profile__c])

    respond_to do |format|
      if (@participant_profile = ParticipantProfile__c.create participant_profile) 
        format.html { redirect_to participant_participant_profile_path(@participant, @participant_profile),
          notice: 'Participant profile was successfully created.' }
        format.json { render json: @participant_profile, status: :created, location: @participant_profile }
      else
        format.html { render action: "new" }
        format.json { render json: @participant.participant_profiles.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /participant_profiles/1
  # PUT /participant_profiles/1.json
  def update
    @participant = Participant__c.find(request[:participant_id])
    @participant_profile = ParticipantProfile__c.find(params[:id])

    params[:participant_profile__c].keys.each do |key|
      @participant_profile[key] = params[:participant_profile__c][key]
      puts "---" + params[:participant_profile__c][key]
    end

    result = @participant_profile.save
    puts result
    respond_to do |format|
      if result
        format.html { redirect_to [@participant, @participant_profile],
          notice: 'Participant profile was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @participant.participant_profile.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participant_profiles/1
  # DELETE /participant_profiles/1.json
  def destroy
    @participant = Participant__c.find(request[:participant_id])
    @participant_profile = ParticipantProfile__c.find(params[:id])
    @participant_profile.delete

    respond_to do |format|
      format.html { redirect_to participant_participant_profiles_url }
      format.json { head :ok }
    end
  end
end

source/app/helpers/participant_profiles_helper.rb
module ParticipantProfilesHelper
end

source/app/views/participant_profiles/_form.html.haml
= form_for(@participant_profile, :url => "/participants/#{@participant['Id']}/participant_profiles/#{@participant_profile['Id']}", :action => @operation, :html => {:class => "nifty_form"}) do |form|
  - ParticipantProfile__c.attributes.select {|a| ParticipantProfile__c.updateable?(a)}.each do |attr|
    %field
      / double between Owner and OwnerId
    - unless attr == 'Owner'
      = form.label attr, ParticipantProfile__c.label_for(attr)
      - case ParticipantProfile__c.field_type(attr)
      - when "date"
        / todo, it generates participant__c[Date_of_Birth__c(1i)]  (2i)  (3i)
        = form.text_field attr, :class => "datepicker", :value => @participant[attr]
      - when "boolean"
        = form.check_box attr
      - when "multipicklist"
      - when "picklist"
        - puts "Rendering picklist for #{attr}, value is #{@participant[attr]}, type is #{ParticipantProfile__c.field_type(attr)}"
        = form.select attr, ParticipantProfile__c.picklist_values(attr).collect {|p| [p["label"], p["value"]]}, :multiple => (ParticipantProfile__c.field_type(attr) == "multipicklist")
      - when 'reference'
        - unless @participant[attr].nil? || @participant[attr].empty?
          = @participant[attr]
        - else
          / skipping OwnerId  / Owner
      - when 'email'
        / email is an unique field, update does not really work well here.
        - if !@participant.persisted?
          = form.email_field attr
        - else
          / TODO not updating this unique field
          = @participant[attr]
      - else
        = form.text_field attr
    %br/
  - if @participant_profile.persisted?
    = form.submit 'Update Participant'
  - else
    = form.submit 'Create Participant'

source/app/views/participant_profiles/edit.html.haml
%h1 Editing participant_profile
= render 'form'
= link_to 'Show', participant_participant_profile_path(@participant['Id'], @participant_profile['Id'])
|
\#{link_to 'Back', participant_participant_profiles_path}

source/app/views/participant_profiles/index.html.haml
%h1 Listing participant_profiles
- unless @participant_profiles.empty?
  %table
    %tr
      - @participant_profiles[0].attributes.keys.each do |key|
        %th{:align => "left"}= key.underscore.humanize
      %th
      %th
      %th
    - @participant_profiles.each do |participant_profile|
      %tr
        - participant_profile.attributes.keys.each do |key|
          %td
            = participant_profile.attributes[key]
        %td= link_to 'Show', participant_participant_profile_path(@participant ,participant_profile)
        / TODO wait until gem fix for unique entry
        / <td><haml:loud> link_to 'Edit', edit_participant_participant_profile_path(@participant, participant_profile) </haml:loud></td>
        %td= link_to 'Destroy', participant_participant_profile_path(@participant, participant_profile), confirm: 'Are you sure?', method: :delete
- else
  You have no outstanding Profile.
%br/
= link_to 'New Participant profile', new_participant_participant_profile_path
|
\#{link_to 'Go back to Participant', participant_path(@participant)}

source/app/views/participant_profiles/new.html.haml
%h1 New participant_profile
= render 'form'
= link_to 'Back', participant_participant_profiles_path

source/app/views/participant_profiles/show.html.haml
- @participant_profile.attributes.keys.each do |key|
  / doubled Owner and OwnerId
  - unless key == 'Owner'
    %p
      %b= key.underscore.humanize
      = @participant_profile.attributes[key]
/ <haml:loud> link_to 'Edit', edit_participant_participant_profile_path(@participant['Id'], @participant_profile['Id']) </haml:loud> |
= link_to 'Back', participant_participant_profiles_path