source/config/routes.rb
MyFitness::Application.routes.draw do
  #resources :participant_profiles

  #resources :fitness_goals

  #resources :participants

  resources :participants do
    resources :fitness_goals
    resources :participant_profiles

    collection do
      get 'welcome' #welcome page
      post 'find' #find a participant by email
      get 'list' #list all participants registered in the system
    end

  end
  
  root :to => 'participants#welcome'

end

source/app/models/fitness_goal.rb
class FitnessGoal < ActiveRecord::Base
  belongs_to :participant
end

source/app/controllers/fitness_goals_controller.rb
class FitnessGoalsController < ApplicationController
  include Databasedotcom::Rails::Controller
  #http_basic_authenticate_with :name => "ray", :password => "xxx", :except => :index

  before_filter :init

  def init
    dbdc_client.materialize('Participant__c')
    dbdc_client.materialize('ParticipantProfile__c')
    dbdc_client.materialize('Fitness_Goal__c')

    @dbdc_client = dbdc_client
  end
  
  # GET /fitness_goals
  # GET /fitness_goals.json
  def index
    @participant = Participant__c.find(request[:participant_id])
    @fitness_goals = Fitness_Goal__c.query("Participant__r.Id=" + "'#{request[:participant_id]}'")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fitness_goals }
    end
  end

  # GET /fitness_goals/1
  # GET /fitness_goals/1.json
  def show
    @participant = Participant__c.find(request[:participant_id])
    @fitness_goal = Fitness_Goal__c.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fitness_goal }
    end
  end

  # GET /fitness_goals/new
  # GET /fitness_goals/new.json
  def new
    @participant = Participant__c.find(request[:participant_id])
    @fitness_goal = Fitness_Goal__c.new
    @operation = 'create'

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fitness_goal }
    end
  end

  # GET /fitness_goals/1/edit
  def edit
    @participant = Participant__c.find(request[:participant_id])
    @fitness_goal = Fitness_Goal__c.find(params[:id])
    @operation = 'update'
  end

  # POST /fitness_goals
  # POST /fitness_goals.json
  def create
    @participant = Participant__c.find(request[:participant_id])
    params[:fitness_goal__c]['Participant__c'] = @participant['Id']
    @fitness_goal = Fitness_Goal__c.new(params[:fitness_goal__c])
    fitness_goal = Fitness_Goal__c.coerce_params(params[:fitness_goal__c])

    respond_to do |format|
      if (@fitness_goal = Fitness_Goal__c.create fitness_goal)
        format.html { redirect_to participant_fitness_goal_path(@participant, @fitness_goal), notice: 'Fitness goal was successfully created.' }
        format.json { render json: @fitness_goal, status: :created, location: @fitness_goal }
      else
        format.html { render action: "new" }
        format.json { render json: @participant.fitness_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fitness_goals/1
  # PUT /fitness_goals/1.json
  def update
    @participant = Participant__c.find(request[:participant_id])
    @fitness_goal = Fitness_Goal__c.find(params[:id])

    params[:fitness_goal__c].keys.each do |key|
      @fitness_goal[key] = params[:fitness_goal__c][key]
      puts "---" + params[:fitness_goal__c][key]
    end

    result = @fitness_goal.save
    puts result

    respond_to do |format|
      if result
        format.html { redirect_to [@participant, @fitness_goal], notice: 'Fitness goal was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @participant.fitness_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fitness_goals/1
  # DELETE /fitness_goals/1.json
  def destroy
    @participant = Participant__c.find(request[:participant_id])
    @fitness_goal = Fitness_Goal__c.find(params[:id])
    @fitness_goal.delete

    respond_to do |format|
      format.html { redirect_to participant_fitness_goals_url }
      format.json { head :ok }
    end
  end
end

source/app/helpers/fitness_goals_helper.rb
module FitnessGoalsHelper
end

source/app/views/fitness_goals/_form.html.haml
= form_for(@fitness_goal, :url => "/participants/#{@participant['Id']}/fitness_goals/#{@fitness_goal['Id']}", :action => @operation, :html => {:class => "nifty_form"}) do |form|
  - Fitness_Goal__c.attributes.select {|a| Fitness_Goal__c.updateable?(a)}.each do |attr|
    %field
      / double between Owner and OwnerId
    - unless attr == 'Owner'
      = form.label attr, Fitness_Goal__c.label_for(attr)
      - case Fitness_Goal__c.field_type(attr)
      - when "date"
        / todo, it generates participant__c[Date_of_Birth__c(1i)]  (2i)  (3i)
        = form.text_field attr
      - when "boolean"
        = form.check_box attr
      - when "multipicklist"
      - when "picklist"
        - puts "Rendering picklist for #{attr}, value is #{@participant[attr]}, type is #{Fitness_Goal__c.field_type(attr)}"
        = form.select attr, Fitness_Goal__c.picklist_values(attr).collect {|p| [p["label"], p["value"]]}, :multiple => (Fitness_Goal__c.field_type(attr) == "multipicklist")
      - when 'reference'
        - unless @participant[attr].nil? || @participant[attr].empty?
          = @participant[attr]
        - else
          / skipping OwnerId  / Owner
      - when 'email'
        / email is an unique field, update does not really work well here.
        - if !@participant.persisted?
          = form.email_field attr
        - else
          / TODO not updating this unique field
          = @participant[attr]
      - else
        = form.text_field attr
    %br/
  - if @fitness_goal.persisted?
    = form.submit 'Update Fitness Goal'
  - else
    = form.submit 'Create Fitness Goal'

source/app/views/fitness_goals/edit.html.haml
%h1 Editing fitness_goal
= render 'form'
= link_to 'Show', participant_fitness_goal_path(@participant['Id'], @fitness_goal['Id'])
|
\#{link_to 'Back', participant_fitness_goals_path}

source/app/views/fitness_goals/index.html.haml
%h1 Listing fitness_goals
- unless @fitness_goals.empty?
  %table
    %tr
      - @fitness_goals[0].attributes.keys.each do |key|
        %th{:align => "left"}= key.underscore.humanize
      %th
      %th
      %th
    - @fitness_goals.each do |fitness_goal|
      %tr
        - fitness_goal.attributes.keys.each do |key|
          %td
            = fitness_goal.attributes[key]
        %td= link_to 'Show', participant_fitness_goal_path(@participant ,fitness_goal)
        / TODO wait until gem fix for unique entry
        / <td><haml:loud> link_to 'Edit', edit_participant_fitness_goal_path(@participant, fitness_goal) </haml:loud></td>
        %td= link_to 'Destroy', participant_fitness_goal_path(@participant, fitness_goal), confirm: 'Are you sure?', method: :delete
- else
  You have no outstanding Fitness Goal.
%br/
= link_to 'New Fitness goal', new_participant_fitness_goal_path
|
\#{link_to 'Go back to Participant', participant_path(@participant)}

source/app/views/fitness_goals/new.html.haml
%h1 New fitness_goal
= render 'form'
= link_to 'Back', participant_fitness_goals_path

source/app/views/fitness_goals/show.html.haml
- @fitness_goal.attributes.keys.each do |key|
  / doubled Owner and OwnerId
  - unless key == 'Owner'
    %p
      %b= key.underscore.humanize
      = @fitness_goal.attributes[key]
/ <haml:loud> link_to 'Edit', edit_participant_fitness_goal_path(@participant['Id'], @fitness_goal['Id']) </haml:loud> |
= link_to 'Back', participant_fitness_goals_path