source/config/routes.rb
MyFitness::Application.routes.draw do
  #resources :participant_profiles

  #resources :fitness_goals

  #resources :participants

  resources :participants do
    resources :fitness_goals
    resources :participant_profiles

    collection do
      get 'welcome' #welcome page
      post 'find' #find a participant by email
      get 'list' #list all participants registered in the system
    end

  end
  
  root :to => 'participants#welcome'

end

source/app/models/participant.rb
class Participant < ActiveRecord::Base 
  has_many :participant_profiles, :class_name => "ParticipantProfile", :foreign_key => "participant_id"
  has_many :fitness_goals, :class_name => "FitnessGoal", :foreign_key => "participant_id"
end

source/app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  include Databasedotcom::Rails::Controller
  #http_basic_authenticate_with :name => "ray", :password => "xxx", :except => :index

  before_filter :init

  def init
    dbdc_client.materialize('Participant__c')
    dbdc_client.materialize('ParticipantProfile__c')
    dbdc_client.materialize('Fitness_Goal__c')

    dbdc_client.debugging = true
    @dbdc_client = dbdc_client    
  end

  # GET /participants
  # GET /participants.json
  def list
    @participants = Participant__c.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @participants }
    end
  end

  def index
    redirect_to welcome_participants_path
  end

  # welcome page
  def welcome
    @participant = Participant__c.new
    @operation = 'POST'

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @participants }
    end
  end

  def find
    if !params[:participant__c]['Email__c'].empty?
      @participant = Participant__c.query(
        "Email__c ='#{params[:participant__c]['Email__c']}' limit 1"
        )
    end

    if @participant.empty?
      redirect_to params.merge!(:action => "new")
      return
    else
      redirect_to participant_path(@participant.first['Id'])
      return
    end
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
    @participant = Participant__c.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/new
  # GET /participants/new.json
  def new
    @participant = Participant__c.new
    @operation = 'create'

    unless params[:participant__c][:Email__c].empty?
      @participant["Email__c"] = params[:participant__c][:Email__c]
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/1/edit
  def edit
    @participant = Participant__c.find(params[:id])
    @operation = 'update'
    #@participant = Participant.find(params[:id])
  end

  # POST /participants
  # POST /participants.json
  def create
    participant = Participant__c.coerce_params(params[:participant__c])
    respond_to do |format|
      if (@participant = Participant__c.create participant)
        @participant.reload
        format.html { redirect_to participant_path(@participant), notice: 'Participant was successfully created.' }
        format.json { render json:participant_path(@participant), status: :created, location: @participant }
      else
        format.html { render action: "new" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /participants/1
  # PUT /participants/1.json
  def update
    @participant = Participant__c.find(params[:id])

    params[:participant__c].keys.each do |key|
      @participant[key] = params[:participant__c][key]
      puts "---" + params[:participant__c][key]
    end
    # TODO GEM defect, does not allow update to records with unique entries.
    #result = @participant.save
    result = @participant.update_attributes(params[:participant__c])
    puts result
    respond_to do |format|
      if result
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant = Participant__c.find(params[:id])
    @participant.delete

    respond_to do |format|
      format.html { redirect_to participants_url }
      format.json { head :ok }
    end
  end
end

source/app/helpers/participants_helper.rb
module ParticipantsHelper
end

source/app/views/participants/_form.html.haml
= form_for @participant, :url => { :action => @operation }, :html => {:class => "nifty_form"} do |form|
  - Participant__c.attributes.select {|a| Participant__c.updateable?(a)}.each do |attr|
    %field
      / double between Owner and OwnerId
    - unless attr == 'Owner'
      = form.label attr, Participant__c.label_for(attr)
      - case Participant__c.field_type(attr)
      - when "date"
        / todo, it generates participant__c[Date_of_Birth__c(1i)]  (2i)  (3i)
        = form.text_field attr, :class => "datepicker", :value => @participant[attr]
      - when "boolean"
        = form.check_box attr
      - when "multipicklist"
      - when "picklist"
        - puts "Rendering picklist for #{attr}, value is #{@participant[attr]}, type is #{Participant__c.field_type(attr)}"
        = form.select attr, Participant__c.picklist_values(attr).collect {|p| [p["label"], p["value"]]}, :multiple => (Participant__c.field_type(attr) == "multipicklist")
      - when 'reference'
        - unless @participant[attr].nil? || @participant[attr].empty?
          = @participant[attr]
        - else
          / skipping OwnerId  / Owner
      - when 'email'
        / email is an unique field, update does not really work well here.
        - if !@participant.persisted?
          = form.email_field attr
        - else
          / TODO not updating this unique field
          = @participant[attr]
      - else
        = form.text_field attr
    %br/
  - if @participant.persisted?
    = form.submit 'Update Participant Profile'
  - else
    = form.submit 'Create Participant Profile'

source/app/views/participants/edit.html.haml
%h1 Editing participant
= render 'form'
= link_to 'Show', participant_path(@participant)
|
\#{link_to 'Back', participants_path}

source/app/views/participants/list.html.haml
%h1 Listing participants
- unless @participants.empty?
  %table
    %tr
      - @participants[0].attributes.keys.each do |key|
        %th{:align => "left"}= key.underscore.humanize
      %th
      %th
      %th
    - @participants.each do |participant|
      %tr
        - participant.attributes.keys.each do |key|
          %td
            = participant.attributes[key]
        %td= link_to 'Show', participant_path(participant)
        / TODO wait until gem fix for unique entry
        / <td><haml:loud> link_to 'Edit', edit_participant_path(participant) </haml:loud></td>
        %td= link_to 'Destroy', participant_path(participant), confirm: 'Are you sure?', method: :delete
- else
  everything is empty
%br/
= link_to 'New Participant', new_participant_path

source/app/views/participants/new.html.haml
%h1 New participant
= render 'form'
= link_to 'Back', participants_path

source/app/views/participants/show.html.haml
- @participant.attributes.keys.each do |key|
  / doubled Owner and OwnerId
  - unless key == 'Owner'
    %p
      %b= key.underscore.humanize
      = @participant.attributes[key]
/ TODO wait until gem fix for unique entry
/ <haml:loud> link_to 'Edit', edit_participant_path(@participant) </haml:loud> |
= link_to 'Back', participants_path
|
\#{link_to 'Show My Fitness Goals', participant_fitness_goals_path(@participant)}
|
\#{link_to 'Show My Participant Profiles', participant_participant_profiles_path(@participant)}

source/app/views/participants/welcome.haml
%h1 Welcome to Fitness Tracker
If you are new user, entering your e-mail address will create a new account for you.
If you are an existing user, entering your e-mail will retrieve your existing profile.

= form_for(@participant, :url => find_participants_path, :method => "#{@operation}", :html => {:class => "nifty_form"}) do |form|
  = form.label "Email__c", Participant__c.label_for("Email__c")
  = form.email_field "Email__c"
  %br/
  = form.submit :value => "Start here"